settings:
  title: 'Uptime Page'
  url: 'https://status.dplayzgames06.tk' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Online'
  notAllmonitorsOperational: 'Not All Systems Online'
  monitorLabelOperational: 'Online'
  monitorLabelNotOperational: 'Offline'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: dp-web # unique identifier
    name: Website
    description: 'Official Website of dplayz Games' # default=empty
    url: 'https://dplayzgames06.tk/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: true # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: dp-files # unique identifier
    name: File Server
    url: 'https://files.dplayzgames06.tk/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: true # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: dp-linkservice1 # unique identifier
    name: Link Service
    url: 'https://dpg06.tk/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: true # should fetch follow redirects, default=false
    linkable: false

  - id: dp-code-server-container
    name: Private Code Server Instance
    url: 'https://code-server.dplayzgames06.tk' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: true # should fetch follow redirects, default=false
    linkable: false
